// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace WhatsForDinner.ViewControllers
{
	public partial class FavoriteRecipesViewController : BaseWhatsForDinnerViewController
	{
		public FavoriteRecipesViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
