// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using WhatsForDinner.Presenters;
using WhatsForDinner.Presenters.Contracts;
using WhatsForDinner.ViewControllers.Contracts;

namespace WhatsForDinner.ViewControllers
{
	public partial class LoginViewController : BaseWhatsForDinnerViewController, LoginViewControllerInterface
	{
        LoginPresenterInterface Presenter = new LoginPresenter();
        public Action<string, string> LoginButtonClicked { get; set; }
		public LoginViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            LogInButton.TouchUpInside += LogInButton_TouchUpInside;
            Presenter.BindToView(this);
        }

        private void LogInButton_TouchUpInside(object sender, EventArgs e)
        {
            LoginButtonClicked?.Invoke(UsernameTextField.Text, PasswordTextField.Text);
        }

        public void MoveToHomeScreen()
        {
            var homeTabController = ControllerFactory.GetHomeTabController(Storyboard);
            if(homeTabController != null)
            {
                UIView.Transition(UIApplication.SharedApplication.KeyWindow, 1f, UIViewAnimationOptions.TransitionFlipFromRight, () =>
                {
                    UIApplication.SharedApplication.KeyWindow.RootViewController = homeTabController;
                }, null);
            }
        }
    }
}
