// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using WhatsForDinner.JsonModels;
using WhatsForDinner.Presenters;
using WhatsForDinner.Presenters.Contracts;
using WhatsForDinner.TableViewCells;
using WhatsForDinner.TableViewSources;
using WhatsForDinner.ViewControllers.Contracts;

namespace WhatsForDinner.ViewControllers
{
    public partial class RecipesViewController : BaseWhatsForDinnerViewController, RecipesViewControllerInterface
    {
        public Action<int> RecipeSelected
        {
            get
            {
                return (RecipesTableView.Source as RecipesTableViewSource).RecipeSelected;
            }
            set
            {
                (RecipesTableView.Source as RecipesTableViewSource).RecipeSelected = value;
            }
        }
        public RecipeByIngredientJsonModel[] Recipes { get; set; }
        RecipesPresenterInterface Presenter = new RecipesPresenter();
        public RecipesViewController(IntPtr handle) : base(handle)
        {
        }
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            RecipesTableView.RegisterNibForCellReuse(RecipeTableViewCell.Nib, RecipeTableViewCell.Key);
            RecipesTableView.Source = new RecipesTableViewSource(this);
            Presenter.BindToView(this, Recipes);
        }

        public void MoveToRecipeViewController(RecipeJsonModel recipe, RecipeByIngredientJsonModel recipeByIngredient)
        {
            InvokeOnMainThread(() => NavigationController.PushViewController(ControllerFactory.GetRecipeViewController(Storyboard, recipe, recipeByIngredient), false));
        }
    }
}
