// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using WhatsForDinner.JsonModels;
using WhatsForDinner.Presenters;
using WhatsForDinner.Presenters.Contracts;
using WhatsForDinner.TableViewCells;
using WhatsForDinner.TableViewSources;
using WhatsForDinner.ViewControllers;
using WhatsForDinner.ViewControllers.Contracts;

namespace WhatsForDinner
{
	public partial class ShoppingListViewController : BaseWhatsForDinnerViewController, ShoppingIngredientsViewControllerInterface
    {
        ShoppingListPresenterInterface Presenter = new ShoppingListPresenter();

        public IngredientJsonModel[] MissingIngredients { get; set; }
        public IngredientJsonModel[] UsedIngredients { get; set; }

        public ShoppingListViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            ShoppingListTableView.RegisterNibForCellReuse(ShoppingListTableViewCell.Nib, ShoppingListTableViewCell.Key);
            ShoppingListTableView.Source = new ShoppingListTableViewSource(MissingIngredients, UsedIngredients);
            Presenter.BindToView(this);
        }
    }
}
